spring:
  application:
    name: beacon
  # 使用高性能的 caffeine 做缓存，来缓存badge，设置最大 2000 个 badge，访问 600 秒后过期.
  cache:
    type: caffeine
    cache-names: badge
    caffeine:
      spec: maximumSize=2000,expireAfterAccess=600s

# 服务端口，将默认为2020.
server:
  port: 2020

# 日志相关的简单配置.
logging:
  file: logs/beacon.log
  level:
    root: info
    org:
      apache: error
      springframework: error